FROM apache/airflow:2.5.0

# Switch to airflow user BEFORE pip install
USER airflow

RUN pip install \
    apache-airflow-providers-apache-spark==4.1.0 \
    kafka-python==2.0.2 \
    pymongo==4.4.1 \
    faker==15.3.0 \
    redis==5.0.1
